# Generated by Django 4.2 on 2026-05-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_profile_phone_char"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verification_token",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('accounts', 'Profile').objects.update(
                email_verified=True,
            ),
            migrations.RunPython.noop,
        ),
    ]
