version: '3.3'
services:
  nginx:
    image: nginx:1.15-alpine
    restart: always
    logging:
      driver: gcplogs
    volumes:
      - ./docker/data/nginx:/etc/nginx/conf.d/
      - backend_media:/code/media/
      - ./static:/code/static/
      - ./docker/data/certbot/conf:/etc/letsencrypt
      - ./docker/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./docker/data/certbot/conf:/etc/letsencrypt
      - ./docker/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  backend:
    container_name: backend
    restart: always
    logging:
      driver: gcplogs
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
      - backend_media:/code/media/
    env_file:
      - './.env'
    environment:
      DEBUG: 'false'

volumes:
  backend_static:
  backend_media:
