# Generated by Django 5.2.14 on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(
                choices=[
                    ('futsal_booking', 'Futsal Booking'),
                    ('opponent_finder', 'Opponent Finder'),
                    ('general_inquiry', 'General Inquiry'),
                    ('other', 'Other'),
                ],
                db_index=True,
                default='general_inquiry',
                max_length=32,
            ),
        ),
    ]
