# Generated by Django 5.2.14 on 2026-05-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_contact_admin_response"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_youtube_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube link for the About page video (watch, share, or embed URL).",
                        max_length=500,
                    ),
                ),
                (
                    "home_youtube_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube link for the homepage “Welcome” section video.",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "site content",
                "verbose_name_plural": "site content",
            },
        ),
    ]
