# Generated by Django 5.2.14 on 2026-05-29 09:13

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _copy_site_content_settings(apps, schema_editor):
    Old = apps.get_model('core', 'SiteContentSettings')
    New = apps.get_model('core', 'SiteConfiguration')
    old = Old.objects.filter(pk=1).first()
    defaults = {
        'about_youtube_url': 'https://www.youtube.com/watch?v=_lHve-9EUK0',
        'home_youtube_url': 'https://www.youtube.com/watch?v=_lHve-9EUK0',
        'facebook_url': 'https://www.facebook.com/futnetnepal',
        'twitter_url': 'https://twitter.com/futnetnepal',
        'instagram_url': 'https://www.instagram.com/futnetnepal',
        'partner_bullets': (
            'List venues and manage visibility\n'
            'Sponsor matches and local leagues\n'
            'Co-host events with our player network'
        ),
        'about_hero_subtitle': (
            'Connecting futsal players, venues, and communities across Nepal.'
        ),
        'partner_hero_subtitle': (
            "Grow with Nepal's futsal community — venues, sponsors, and organizers welcome."
        ),
    }
    if old:
        defaults['about_youtube_url'] = old.about_youtube_url or defaults['about_youtube_url']
        defaults['home_youtube_url'] = old.home_youtube_url or defaults['home_youtube_url']
    New.objects.update_or_create(pk=1, defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_seed_default_youtube_urls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CMSPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/pages/heroes"
                    ),
                ),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("meta_description", models.TextField(blank=True, max_length=320)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("show_in_navbar", models.BooleanField(db_index=True, default=False)),
                ("show_in_footer", models.BooleanField(db_index=True, default=False)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS page",
                "verbose_name_plural": "CMS pages",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(default="Futnet Nepal", max_length=120),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="site/branding"),
                ),
                (
                    "favicon",
                    models.FileField(blank=True, null=True, upload_to="site/branding"),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Default SEO description for public pages.",
                        max_length=320,
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated default keywords.",
                        max_length=255,
                    ),
                ),
                (
                    "about_hero_eyebrow",
                    models.CharField(blank=True, default="Our story", max_length=120),
                ),
                (
                    "about_hero_title",
                    models.CharField(blank=True, default="About Us", max_length=200),
                ),
                (
                    "about_hero_subtitle",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "about_content",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "about_image",
                    models.ImageField(blank=True, null=True, upload_to="site/about"),
                ),
                ("about_youtube_url", models.URLField(blank=True, max_length=500)),
                (
                    "about_cta_label",
                    models.CharField(
                        blank=True, default="Join the community", max_length=80
                    ),
                ),
                (
                    "partner_hero_eyebrow",
                    models.CharField(blank=True, default="Collaborate", max_length=120),
                ),
                (
                    "partner_hero_title",
                    models.CharField(
                        blank=True, default="Partner With Us", max_length=200
                    ),
                ),
                (
                    "partner_hero_subtitle",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "partner_content",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "partner_bullets",
                    models.TextField(
                        blank=True,
                        help_text="One partnership benefit per line (shown as a checklist).",
                    ),
                ),
                (
                    "partner_image",
                    models.ImageField(blank=True, null=True, upload_to="site/partner"),
                ),
                (
                    "home_welcome_eyebrow",
                    models.CharField(blank=True, default="Welcome to", max_length=120),
                ),
                (
                    "home_welcome_title",
                    models.CharField(
                        blank=True, default="Futnet Nepal", max_length=200
                    ),
                ),
                (
                    "home_welcome_content",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                ("home_youtube_url", models.URLField(blank=True, max_length=500)),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="Futnet Nepal Pvt. Ltd.", max_length=200
                    ),
                ),
                (
                    "contact_address",
                    models.TextField(blank=True, default="Balaju-16, Kathmandu, Nepal"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, default="info@futnetnepal.com", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, default="+977 9840177381", max_length=40
                    ),
                ),
                ("contact_website", models.URLField(blank=True, max_length=500)),
                ("facebook_url", models.URLField(blank=True, max_length=500)),
                ("twitter_url", models.URLField(blank=True, max_length=500)),
                ("instagram_url", models.URLField(blank=True, max_length=500)),
                ("youtube_social_url", models.URLField(blank=True, max_length=500)),
                ("linkedin_url", models.URLField(blank=True, max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "site configuration",
                "verbose_name_plural": "site configuration",
            },
        ),
        migrations.RunPython(_copy_site_content_settings, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="SiteContentSettings",
        ),
    ]
