from django.urls import path
from apps.core import views
from apps.core import messenger_views
from apps.accounts.views import UserProfileView
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.global_search, name='global_search'),
    path('about', views.about, name='about'),
    path('partnerwithus', views.partnerwithus, name='partnerwithus'),
    path('contact', views.ContactView.as_view(), name='contact'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('review', views.review, name='review'),
    path('venuelist/', views.VenueListView.as_view(), name='venuelist'),
    path('venues/<slug:venue_slug>/', views.VenueDetailView.as_view(), name='venue_detail'),
    path('venues/<slug:venue_slug>/book/', views.venue_book, name='venue_book'),
    path('posts/<int:post_id>/interest/', views.post_toggle_interest, name='post_toggle_interest'),
    path('posts/<int:post_id>/react/', views.post_toggle_reaction, name='post_toggle_reaction'),
    path('posts/<int:post_id>/comments/', views.post_comments, name='post_comments'),
    path('posts/<int:post_id>/comments/add/', views.post_add_comment, name='post_add_comment'),
    path('posts/<int:post_id>/confirm-match/', views.post_confirm_match, name='post_confirm_match'),
    path('posts/<int:post_id>/cancel-confirmation/', views.post_cancel_confirmation, name='post_cancel_confirmation'),
    path('notifications/poll/', views.notifications_poll, name='notifications_poll'),
    path('notifications/', views.notifications_list, name='notifications_list'),
    path('notifications/<int:notification_id>/read/', views.notification_mark_read, name='notification_mark_read'),
    path('notifications/read-all/', views.notifications_mark_all_read, name='notifications_mark_all_read'),
    path('messages/', messenger_views.MessagesView.as_view(), name='messages'),
    path('messages/data/', messenger_views.messages_inbox_data, name='messages_inbox_data'),
    path('messages/c/<int:conversation_id>/', messenger_views.MessagesView.as_view(), name='messages_conversation'),
    path('messages/<slug:post_slug>/', messenger_views.MessagesView.as_view(), name='messages_thread'),
    path('messages/<slug:post_slug>/with/<str:username>/', messenger_views.MessagesView.as_view(), name='messages_with_user'),
    path('conversations/<int:conversation_id>/chat/', messenger_views.dm_chat_thread, name='dm_chat_messages'),
    path('conversations/<int:conversation_id>/chat/send/', messenger_views.dm_chat_send, name='dm_chat_send'),
    path('conversations/<int:conversation_id>/chat/confirm-attendance/', messenger_views.event_confirm_attendance, name='event_confirm_attendance'),
    path('conversations/<int:conversation_id>/chat/decline-attendance/', messenger_views.event_decline_attendance, name='event_decline_attendance'),
    path('conversations/<int:conversation_id>/chat/confirm-match/', messenger_views.event_confirm_match, name='event_confirm_match'),
    path('conversations/<int:conversation_id>/chat/cancel-confirmation/', messenger_views.event_cancel_confirmation, name='event_cancel_confirmation'),
    path('home/<slug:time_slug>/', views.CategoryPostListView.as_view(), name='post-cat'),
    path('get_edit_data/<int:post_id>/', views.get_edit_data, name='get_edit_data'),
    path('update_post/<int:post_id>/', views.update_post, name='update_post'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    
]